Repository Team-Offroad/Offroad-iOS, pull requests merged in 2024-07, with the labels that each got.

#6 [Setting] #5 - 프로젝트 내에 쓰일 폰트 스타일 설정
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Literals/FontLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-Black.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-ExtraBold.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-ExtraLight.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-Light.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-Medium.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-Regular.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Pretendard-Thin.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Add ➕

#12 [Fix/#11] Info.plist에 추가된 폰트 이름에 확장자 추가
  Offroad-iOS/Offroad-iOS.xcworkspace/contents.xcworkspacedata
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#14 [Setting] #13 - Color Literal 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Presentation/ViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Add ➕, Setting ⚙️

#17 [Setting] #16 - FontLiteral 수정(새로운 폰트 추가)
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Literals/FontLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Fonts/Optician-Sans.otf
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
Labels: 🎀 혜린 🎀, Add ➕, Setting ⚙️

#18 [Feat] #9 - 스플래시, 로그인 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_apple_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_apple_logo.imageset/apple_logo_img.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_kakao_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_kakao_logo.imageset/kakao_logo_img.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/offroad_logo_login.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/offroad_logo_splash.svg
  Offroad-iOS/Offroad-iOS/Presentation/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/Login/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/Login/View/LoginView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/View/SplashView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#24 [Setting] #22 - 프로젝트 환경설정 추가 세팅
  .gitignore
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Setting ⚙️

#19 [Feat] #10 - 닉네임 작성 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
  Offroad-iOS/Pods/Pods.xcodeproj/project.pbxproj
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#21 [Feat] #20 - 생년월일 선택 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/NicknameSetting/.gitkeep
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#28 [Feat] #25 - GenderViewController UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#30 [Feat] #23 - HomeView UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_change_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_change_character.imageset/btn_change_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_download.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_download.imageset/btn_download.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_share.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_share.imageset/btn_share.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_change_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_change_title.imageset/icon_change_title.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_character.imageset/img_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_compass.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_compass.imageset/img_compass.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_fire.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_fire.imageset/img_fire.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_offroad_stamp.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_offroad_stamp.imageset/img_offroad_stamp.svg
  Offroad-iOS/Offroad-iOS/Presentation/Home/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomAlmostDoneProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomQuestView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomRecentProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#36 [Feat] #35 - Custom Button 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/OffroadButton.swift
Labels: 🎀 혜린 🎀, Feat 💻

#38 [Add] #37 - UILabel의 줄 간격 조절하는 함수 추가
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
Labels: 🫧 지원 🫧, Add ➕, Setting ⚙️

#32 [Feat] #15 - QuestMapView 기본 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/btn_dot_scope.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/btn_dot_scope.imageset/ios_dot_scope.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icon_list_bullet.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icon_list_bullet.imageset/icon_list_bullet.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icon_place_marker.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icon_place_marker.imageset/icon_place_marker.svg
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/QuestMapListButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapNavigationController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#42 [Feat] #31 - 획득 칭호 CustomPopupView UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/StateToggleButton.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/FontLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_change_character.imageset/btn_change_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_download.imageset/btn_download.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_share.imageset/btn_share.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_change_title.imageset/icon_change_title.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_close.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_close.imageset/icon_close.svg
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/Model/TitleModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/Cell/TitleCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#46 [Feat] #39 - SplashView LoginView 화면 전환 애니메이션 구현
  Offroad-iOS/Offroad-iOS/Presentation/Splash/View/SplashView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#34 [Feat] #33 - QuestQRView, QuestMapNavigationController 기본 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestQR/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestQR/icn_chevron_left.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestQR/icn_chevron_left.imageset/icn_chevron_left.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestQR/icn_square_dashed_cornerLeft.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestQR/icn_square_dashed_cornerLeft.imageset/icn_square_dashed_cornerLeft.svg
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapNavigationController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestNavigationBar.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/ViewControllers/QuestQRViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/Views/QuestQRView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Add ➕, Style 🎨

#43 [Feat] #40 - TabBarController 커스텀
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_home.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_home.imageset/icn_home.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_person.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_person.imageset/icn_person.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_offroadLogo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_offroadLogo.imageset/icn_tabBar_offroadLogo.svg
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/QuestMapListButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#53 [Feat] #48 - Apple Social Login 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Offroad-iOS.entitlements
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/AppleAuthManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/Model/UserModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#57 [Chore] #10 - 키보드 내려가는 동작 구현
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩, Style 🎨

#52 [Feat] #51 - UIView extension popup 애니메이션 구현
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Add ➕

#55 [Feat] #29 - ChoosingCharacterViewController UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_basic_indicator.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_basic_indicator.imageset/img_basic_indicator.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_current_indicator.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_current_indicator.imageset/img_current_indicator.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_human.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_human.imageset/img_human.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_left_button.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_left_button.imageset/img_left_button.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_naked_human.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_naked_human.imageset/img_naked_human.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_red_hair.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_red_hair.imageset/img_red_hair.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_right_button.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_right_button.imageset/img_right_button.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_door_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_door_brown.imageset/img_character_door_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_shadow_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_shadow_brown.imageset/img_character_shadow_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character_brown.imageset/img_complete_ character_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_offroad_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_offroad_logo.imageset/img_offroad_logo.svg
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#56 [Feat] #41 - CompleteChoosingCharacterViewController UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_door_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_door_brown.imageset/img_character_door_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_shadow_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_shadow_brown.imageset/img_character_shadow_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_complete_ character_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_complete_ character_brown.imageset/img_complete_ character_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_offroad_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_offroad_logo.imageset/img_offroad_logo.svg
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/ViewController/CompleteChoosingCharacterViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#60 [Setting] #54 - Moya를 사용한 네트워크 초기 세팅 및 임시 부착
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Request/AdventuresAuthenticationRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventureInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventuresAuthenticationResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/AuthAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/AuthService.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/DTO/Request/SocialLoginRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/DTO/Response/RefreshTokenResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/DTO/Response/SocialLoginResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseTargetType.swift
  Offroad-iOS/Offroad-iOS/Network/Base/ErrorResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Base/MoyaPlugin.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkResult.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/DataModel/.gitkeep
  Offroad-iOS/Offroad-iOS/Network/Emblem/DTO/Response/ChangeEmblemResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/DTO/Response/EmblemInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemService.swift
  Offroad-iOS/Offroad-iOS/Network/Nickname/DTO/Response/NicknameCheckResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Nickname/NicknameAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Nickname/NicknameService.swift
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Request/RegisteredPlaceRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Responce/RegisteredPlaceResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/ProfileUpdateResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Network/Quest/DTO/Response/QuestInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Quest/QuestAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Quest/QuestService.swift
  Offroad-iOS/Offroad-iOS/Network/Service/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#58 [Feat] #44 - 커스텀 탭바 디자인 세부 조정
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/UITabBar+.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestNavigationBar.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#49 [Feat] #45 - QR 코드 카메라 기능 및 권한 요청 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_circle_in_whiteBorder.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_circle_in_whiteBorder.imageset/icn_circle_in_whiteBorder.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_triangle_arrow.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_triangle_arrow.imageset/icn_orange_triangle_arrow.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Models/OffroadPlace.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapNavigationController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestNavigationBar.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/ViewControllers/QuestQRViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/Views/AVCameraPreview.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/Views/QuestQRView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻

#64 [Feat] #62 - HomeView API 통신
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventureInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/AuthAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseTargetType.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/DTO/Response/ChangeEmblemResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemService.swift
  Offroad-iOS/Offroad-iOS/Network/Quest/QuestAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Quest/QuestService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomAlmostDoneProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomQuestView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomRecentProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/Cell/TitleCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#66 [Feat] #61 - NicknameViewController api 연결
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Nickname/NicknameAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Nickname/NicknameService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Network 🌏

#68 [Feat] #65 - 캐릭터 선택 뷰 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_no.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_no.imageset/btn_no.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_yes.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_yes.imageset/btn_yes.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character.imageset/img_complete_ character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character_brown.imageset/img_complete_ character_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_door_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_door_brown.imageset/img_character_door_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_character_shadow_brown.imageset/img_character_shadow_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_complete_ character_brown.imageset/img_complete_ character_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/img_offroad_logo.imageset/img_offroad_logo.svg
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterChoosingResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/ViewController/CompleteChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomAlmostDoneProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#69 [Feat/ #67 - 닉네임, 생년월일, 성별 POST 네트워크 통신
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Network 🌏

#78 [Feat] #63 - 지도 관련 API 통신 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/btn_popup_close.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/btn_popup_close.imageset/btn_popup_close.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_offroadlogo_popupView.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_offroadlogo_popupView.imageset/icn_offroadlogo_popupView.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_place_marker_orange.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_place_marker_orange.imageset/icn_place_marker_orange.svg
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Request/AdventuresAuthenticationRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Request/RegisteredPlaceRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Responce/RegisteredPlaceResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/OffroadNMFMarker.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/PlaceInfoPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/PlaceInfoPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/ViewControllers/QuestQRViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻

#79 [Chore] #72 - 회원가입 뷰에서 에러 처리 및 수정사항 적용
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩, Style 🎨

#75 [Chore] #74 - 캐릭터 선택에 따른 배경색 처리
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
Labels: 🎀 혜린 🎀, Chore 🧩

#82 [Chore] #81 -
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩, Style 🎨

#84 [Feat] #77 - QA 요구사항 1차 반영
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Request/AdventuresPlaceAuthenticationRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Request/AdventuresQRAuthenticationRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventuresPlaceAuthenticationResponsetDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventuresQRAuthenticationResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Models/OffroadPlace.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/PlaceInfoPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/ViewControllers/QuestQRViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestResult/ViewControllers/QuestResultViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestResult/Views/QuestResultView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Fix ⚒️

#86 [Feat] #83 -
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Profile/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/backBarButton.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/backBarButton.imageset/backBarButton.svg
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Refactor 🏭

#87 [Feat] #80 - SVG, Lottie 처리 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Global/Extensions/LottieAnimationView+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/SVGKImage+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIImageView+.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventureInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#89 [Chore] #88 - 버튼 isenabled 수정사항 반영
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩, Style 🎨

#91 [Feat] #90 - 커스텀 백버튼 전체 적용
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
Labels: 🫧 지원 🫧, Add ➕

#93 [Feat] #92 - 백버튼 눌렀을 때 다음 버튼 비활성화
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩

#95 [Feat] #94 - 중복확인 활성화 됐을 때 layer 없애기
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩

#96 [Feat] #76 - 온보딩 완료 후 재접속 시 자동로그인 구현
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/AppleAuthManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#102 [Fix] #100 - QA 2차 수정 후 자잘한 수정
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/PlaceInfoPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, 🎀 혜린 🎀, 🫧 지원 🫧, Fix ⚒️

#107 [Fix/#106] textfield 선택 시 layer 색 변경
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️, Style 🎨

#111 [Fix] #105 - Keychain을 사용한 로그인 로직 수정
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventureInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseTargetType.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/KeychainManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#113 [Fix] #112 - 생년월일 자동이동 및 자동변환
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#121 [Fix] #116 - 생년월일 실시간 유효성 검사 및 자동이동과 다음 버튼 로직 수정
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#117 [Fix/#114] 공원 탐험 성공 시 팝업이 뜨지 않는 문제 해결
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/PlaceInfoPopupViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#120 [Fix] #118 탐험 관련 QA 수정(1차)
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestResult/Views/QuestResultView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#122 [Fix] #119 - ChoosingCharacterView, HomeView QA 수정사항 반영
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/Cell/TitleCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️
