Repository Team-Offroad/Offroad-iOS, pull requests merged in 2024-12, with the labels that each got.

#362 [Fix] #355 - 2차 QA(대면) 수정사항 일부 반영
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIScrollView+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponDetail/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponDetail/icn_couponDetail_keyAndLock.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponDetail/icn_couponDetail_keyAndLock.imageset/icn_couponDetail_keyAndLock.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponDetail/icn_couponDetail_ticket.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponDetail/icn_couponDetail_ticket.imageset/icn_couponDetail_ticket.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_coupon.imageset/img_coupon.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_key.imageset/Frame 1261161039.svg
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/CouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Fix ⚒️

#363 [Del] #361 - 필요 없는 이미지 애셋 제거
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_human.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_human.imageset/img_human.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_naked_human.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_naked_human.imageset/img_naked_human.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_red_hair.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Character/img_red_hair.imageset/img_red_hair.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_no.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_no.imageset/btn_no.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_yes.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/btn_yes.imageset/btn_yes.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_1.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_1.imageset/ios_[ver]get_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_2.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_2.imageset/ios_[ver]get_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_3.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_3.imageset/ios_[ver]get_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_character.imageset/img_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_character_profile.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_character_profile.imageset/img_character_profile.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/character_1_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/character_1_logo.imageset/ios_character profile.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/character_2_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/character_2_logo.imageset/ios_character profile.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/character_3_logo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/character_3_logo.imageset/ios_character profile.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/coffee_coupon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/coffee_coupon.imageset/Rectangle 509075.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_navermapLocationOverlay_subIcon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_navermapLocationOverlay_subIcon.imageset/icn_navermapLocationOverlay_subIcon.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_circle_in_whiteBorder.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_circle_in_whiteBorder.imageset/icn_circle_in_whiteBorder.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_offroadLogo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_offroadLogo.imageset/icn_tabBar_offroadLogo.svg
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Del 🪣

#359 [Fix] #358 - 공지사항 푸시 리다이렉션 로직 수정
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#366 [Fix] #365 - ErrorResponseDTO 사용할 수 있도록 개선
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift
  Offroad-iOS/Offroad-iOS/Network/Base/ErrorResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkResult.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift
  Offroad-iOS/Offroad-iOS/Network/Notice/NoticeService.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Network 🌏

#373 [Fix] #367 - 온보딩 약관동의 뷰 개선
  Offroad-iOS/Offroad-iOS/Network/Base/MoyaPlugin.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/MarketingConsent/ViewController/MarketingConsentViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#374 [Feat] #370 - 채팅 로그 뷰 무한스크롤 구현
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatPostResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewModel/CharacterChatLogViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#378 [Chore] #376 - 바뀐 MoyaPlugin 대응
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterDetailViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩

#382 [Refactor] #375 - 채팅 로그 무한스크롤 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Loading/ScrollLoading.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Loading/ScrollLoadingCollectionView.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIScrollView+.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatPostResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewModel/CharacterChatLogViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogFooter.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩, Refactor 🏭, Style 🎨

#386 [Feat] #372 - 캐릭터 채팅 읽음 여부
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatReadGetResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Network 🌏

#390 [Fix] #387 - 온보딩 뷰 2차 QA 수정사항 적용
  Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#391 [Refactor] #389 - 온보딩 리팩토링
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Refactor 🏭

#393 [Fix] #385 - 캐릭터 채팅 동작 개선
  Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatBox.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Fix ⚒️, Style 🎨

#395 [Add] #383 - 다크 테마 앱 아이콘 적용
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon_Dark.png
Labels: Add ➕

#401 [Fix] #398 - 3차 QA 온보딩(닉네임, 생년월일, 성별 뷰) 수정사항 적용
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#402 [Fix] #392 - 캐릭터 선택 뷰 버그 수정
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterChoosingResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/ProfileUpdateRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#403 [Fix] #396 - 홈 화면 기본 로티 적용
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#408 [Fix] #405 - QA 수정사항 반영
  Offroad-iOS/Offroad-iOS/Global/MyInfoManager/MyInfoManager.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/icn_characterList_babyCharacter.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/icn_characterList_babyCharacter.imageset/icn_characterList_babyCharacter.svg
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#407 [Chore] #404 - 닉네임 뷰 에러처리 수정사항 적용
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩

#411 [Fix] #409 - 3차 QA 수정사항 반영
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_chat.imageset/btn_chat.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/splach_logo.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/splach_logo@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/splach_logo@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_orb_logo_login.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_orb_logo_login.imageset/img_orb_logo_login.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/splach_logo.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/splach_logo1.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/splach_logo2.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_orb_logo_splash.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_orb_logo_splash.imageset/img_orb_logo_splash.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_orbLogo.imageset/icn_tabBar_orbLogo.svg
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/View/LoginView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/View/SplashView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/ORBTabBarShapeView.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#413 [Fix] #412 - QA 긴급 수정
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventuresPlaceAuthenticationResponsetDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/View/LoginView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#417 [Fix] #416 - 쿠폰 사용 후 목록이 비었을 때 cell의 갯수가 최신화되지 않는 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#418 [Refactor] #380 - 지도 뷰에서 툴팁 로직 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Models/ORBPlaceCategory.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Models/OffroadPlace.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltip.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltipWindow.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/ORBMapListButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/ORBNMFMarker.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/ORBMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/ORBMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Refactor 🏭
