Repository Team-Offroad/Offroad-iOS, pull requests merged in 2024-11, with the labels that each got.

#246 [Fix] #239 - 지도 뷰 및 툴팁 개선, 리팩토링
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertBaseView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertViewExplorationResult.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertBackgroundView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/ORBAlertController.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_navermapLocationOverlay_subIcon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_navermapLocationOverlay_subIcon.imageset/icn_navermapLocationOverlay_subIcon.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_orange_triangle_arrow.imageset/icn_orange_triangle_arrow.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_place_marker_orange.imageset/icn_place_marker_orange.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_placeMarker.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_placeMarker.imageset/icn_questMap_placeMarker.svg
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Adventure/DTO/Response/AdventuresPlaceAuthenticationResponsetDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltip.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltipWindow.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/OffroadNMFMarker.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/UIComponents/QuestMapListButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/PlaceInfoPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Fix ⚒️, Refactor 🏭, Style 🎨

#250 [Fix] #248 - 지도 버그 해결
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#247 [Fix] #221 - 탭바 버튼 디자인 적용
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_home.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_home.imageset/icn_home.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_person.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_person.imageset/icn_person.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_selected.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_selected.imageset/icn_tabBar_home_selected.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_selected.imageset/icn_tabBar_home_selected@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_selected.imageset/icn_tabBar_home_selected@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_unselected.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_unselected.imageset/icn_tabBar_home_unselected.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_unselected.imageset/icn_tabBar_home_unselected@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_home_unselected.imageset/icn_tabBar_home_unselected@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_selected.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_selected.imageset/icn_tabBar_my_selected.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_selected.imageset/icn_tabBar_my_selected@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_selected.imageset/icn_tabBar_my_selected@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_unselected.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_unselected.imageset/icn_tabBar_my_unselected.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_unselected.imageset/icn_tabBar_my_unselected@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_my_unselected.imageset/icn_tabBar_my_unselected@3x.png
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Add ➕, Style 🎨

#252 [Feat] #249 - 리브랜딩된 스타일가이드 적용
  Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/NavigationPopButton.swift
  Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/StateToggleButton.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertBaseView.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/FontLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_circle_in_whiteBorder.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_circle_in_whiteBorder.imageset/icn_circle_in_whiteBorder.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_navermapLocationOverlay_subIcon 1.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_navermapLocationOverlay_subIcon 1.imageset/icn_navermapLocationOverlay_subIcon.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_questMap_placeMarker.imageset/icn_questMap_placeMarker.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_orbLogo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/TabBar/icn_tabBar_orbLogo.imageset/icn_tabBar_orbLogo.svg
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomAlmostDoneProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/Cell/TitleCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/View/DeleteAccountView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Logout/View/LogoutView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/View/NoticePostView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltip.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestResult/Views/QuestResultView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Style 🎨

#254 [Fix] #251 - 회원 탈퇴 로직 수정
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/DeleteAccountRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/AppleAuthManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/ViewController/DeleteAccountViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Logout/ViewController/LogoutViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#256 [Fix] #253 - 탭바 눌렀을 때 item이 바로 선택되지 않던 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#261 [Fix] #255 - 리브랜딩 적용
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/icon_check_circle.imageset/icon_check_circle.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/img_tag.imageset/img_tag.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_change_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_change_title.imageset/btn_change_title.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_chat.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_chat.imageset/btn_chat.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_download.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_download.imageset/btn_download.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_change_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/icon_change_title.imageset/icon_change_title.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_fire.imageset/img_fire.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/offroad_logo_login.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/splach_logo.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/splach_logo@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Login/img_offroad_logo_login.imageset/splach_logo@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/Frame 1261160897.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/btn_character.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/btn_character@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/btn_character@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/Frame 1261160898.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/btn_coupon.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/btn_coupon@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/btn_coupon@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/Frame 1261160900.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/btn_setting.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/btn_setting@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/btn_setting@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/Frame 1261160899.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/btn_title.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/btn_title@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/btn_title@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_character_profile.imageset/img_character_profile.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_character.imageset/img_collected_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_coupon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_coupon.imageset/img_collected_coupon.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_title.imageset/img_collected_title.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_flag.imageset/img_flag.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_setting.imageset/img_setting.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_title_frame.imageset/img_title_frame.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_new_tag.imageset/Component 14.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_new_tag.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_new_tag.imageset/img_new_tag.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_checked.imageset/btn_checked.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/img_required.imageset/img_required.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_ cogwheel.imageset/img_ cogwheel.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_loudspeaker.imageset/img_loudspeaker.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/offroad_logo_splash.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/splach_logo.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/splach_logo1.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Splash/img_offroad_logo_splash.imageset/splach_logo2.png
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
Labels: 🎀 혜린 🎀, Fix ⚒️, Style 🎨

#260 [Fix] #245 - 온보딩(닉네임, 나이) 뷰 수정사항 반영
  Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
Labels: 🫧 지원 🫧, Chore 🧩

#262 [Feat] #258 - 퀘스트 목록 무한 스크롤 구현
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_checkBox.imageset/icn_questList_checkBox.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_giftBox.imageset/icn_questList_giftBox.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/img_quest.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/img_quest.imageset/img_quest.svg
  Offroad-iOS/Offroad-iOS/Network/QuestList/DTO/Response/QuestListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/QuestList/QuestListAPI.swift
  Offroad-iOS/Offroad-iOS/Network/QuestList/QuestListService.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListView.swift
Labels: 🎀 혜린 🎀, Feat 💻

#265 [Feat] #263 - 리프레시 토큰 재발급 로직 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/AppUtility.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/AuthService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/TokenIntercepter.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#268 [Add/#267] 로딩 로티 애셋(loading1.json, loading2.json) 추가
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Lotties/loading1.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Lotties/loading2.json
Labels: Add ➕

#269 [Feat] #257 - 캐릭터 채팅 UI 구현, 토스트 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/CharacterChat/ORBCharacterChatBox.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/CharacterChat/ORBCharacterChatView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/CharacterChat/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/CharacterChat/ORBCharacterChatWindow.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastManager.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastWindow.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIColor+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UITextView+.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChatView/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChatView/icn_chatView_sendButton.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChatView/icn_chatView_sendButton.imageset/icn_chatView_sendButton.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ofrAlert/ios_ofrAlert_xmark.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ofrAlert/ios_ofrAlert_xmark.imageset/ios_ofrAlert_xmark.svg
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Add ➕, Style 🎨

#272 [Fix] #271 - 공지사항 API 수정사항 반영
  Offroad-iOS/Offroad-iOS/Network/Notice/DTO/Response/NoticeResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/View/NoticePostView.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#280 [Feat] #276 - CharacterChatAPI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Request/CharacterChatPostRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatGetResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatPostResponseDTO.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Network 🌏

#279 [Fix] #274 - 쿠폰 목록 뷰 무한 스크롤 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/DTO/Response/CouponListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AvailableCouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/CouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#283 [Feat] #281 - (로티가 화면 중앙에 오는) 로딩 뷰 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Loading/LoadingView.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#289 [Fix] #232 - 버그 수정
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_door_brown.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_door_brown.imageset/img_character_door_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_character_shadow_brown.imageset/img_character_shadow_brown.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_ character.imageset/img_complete_ character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_choosing_background.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_choosing_background.imageset/img_complete_choosing_background.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_choosing_background.imageset/img_complete_choosing_background@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_complete_choosing_background.imageset/img_complete_choosing_background@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ChoosingCharacter/img_offroad_logo.imageset/img_offroad_logo.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_change_character.imageset/btn_change_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_home_background.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_home_background.imageset/img_home_background.jpg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_home_background.imageset/img_home_background@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_home_background.imageset/img_home_background@3x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_offroad_stamp.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/img_offroad_stamp.imageset/img_offroad_stamp.svg
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/UserInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/CompleteChoosingCharacter/View/CompleteChoosingCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#291 [Feat] #235 - 홈 화면 캐릭터 이미지 다운로드, 캐릭터 변경 버튼 액션 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/ShareableImageProvider.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#293 [Feat] #282 - 무한스크롤 로딩 로티 생성 및 적용
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Loading/ScrollLoadingView.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#297 [Fix] #270 - 버그 일부 수정, png/svg 형식 무관하게 이미지 받아오도록 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIImageView+.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Protocols/SVGFetchable.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/ViewController/NoticeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestQR/ViewControllers/QuestQRViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#300 [Fix] #296 - 버그 해결, 수정
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/PlaceInfoPopup/icn_placeInfoTooltip_orbLogo.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/PlaceInfoPopup/icn_placeInfoTooltip_orbLogo.imageset/icn_placeInfoTooltip_orbLogo.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestMap/icn_offroadlogo_popupView.imageset/icn_offroadlogo_popupView.svg
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatBox.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatWindow.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterDetailViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltip.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#301 [Feat] #298 - 탐험 인증 후 홈 화면 이동 시 로티 애니메이션 적용
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#303 [Fix] #302 - 로딩 로티 적용되지 않던 부분 적용
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertViewExplorationResult.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩, Style 🎨

#305 [Fix] #304 - 캐릭터 채팅 답장 시 답장하기 버튼이 없을 때에도 아코디언 뷰 구현
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatBox.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#310 [Add] #309 - 확정된 앱 아이콘 적용
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon_Dark.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon_Light.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon_Tinted.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Add ➕

#313 [Fix] #308 - 캐릭터 채팅 시 채팅 로그 뷰로 이동했을 때, 여전히 키보드가 올라와 있는 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#315 [Fix] #311 - 캐릭터 상세 뷰의 UI 개선
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩, Style 🎨

#318 [Fix] #316 - 홈 뷰 컴포넌트들의 계층 변경
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩

#322 [Fix] #307 - 캐릭터 목록 뷰에 처음 진입 시, 캐릭터 이미지가 이상하게 뜨는 현상 해결
  Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#323 [Fix] #320 - 홈 화면의 칭호 변경 팝업 관련 문제 수정
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/ViewController/TitlePopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#321 [Feat] #299 - 전송 버튼 누른 후 캐릭터 답장 오기 전까지 전송 버튼 비활성화
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#325 [Fix] #324 - 캐릭터 채팅 API 중 500에러 대응
  Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkResult.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogCell.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩, Style 🎨, Network 🌏

#326 [Feat] #312 - 캐릭터 목록 중 획득하지 않은 캐릭터 탭 제한
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#329 [Fix] #327 - 홈 뷰와 마이페이지의 새로고침 로직 개선
  Offroad-iOS/Offroad-iOS/Global/MyInfoManager/MyInfoManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterDetailViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#336 [Fix] #328 - ORBSegmentedControl에서 스크롤 중에 Segment를 탭 하면 이상하게 동작하는 문제
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#335 [Fix] #334 - 채팅 실패 시 말풍선 사라지는 로직 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/UICollectionView+.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#342 [Chore] #333 - 자잘한 UI 개선
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/baby.imageset/Frame 1261160926.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/icn_characterDetail_orbCharacter.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/icn_characterDetail_orbCharacter.imageset/icn_characterDetail_orbCharacter.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/icn_characterList_babyCharacter.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/icn_characterList_babyCharacter.imageset/icn_characterList_babyCharacter.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponListView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩, Style 🎨

#343 [Fix] #341 - 쿠폰 상세 뷰 스크롤 가능하도록 변경
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Style 🎨

#345 [Fix] #306 - 캐릭터 채팅 시 원하는 캐릭터 ID별로 채팅 요청하는 기능 구현
  Offroad-iOS/Offroad-iOS/Global/Components/NavigationController/ORBNavigationController.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/CharacterChatService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ORBCharacterChatManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#349 [Fix] #348 - refreshToken 만료 시 로그인이 되지 않던 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#350 [Fix] #337 - 온보딩 2차 스프린트 QA 수정사항 적용
  Offroad-iOS/Offroad-iOS/Global/Extensions/Character+.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#351 [Feat] #346 - 셀 선택 시 탭 피드백 적용
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/CouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/QuestMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Fix ⚒️

#353 [Feat] #292 - 고객 문의 뷰 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_chat.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_chat.imageset/img_chat.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/CustomerInquiry /View/CustomerInquiryView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/CustomerInquiry /ViewController/CustomerInquiryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/View/DeleteAccountView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Model/SettingBaseModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/PlayGuide/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/PrivacyPolicy/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/TermsOfService/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#354 [Fix] #347 - 대표 캐릭터 변경 후 캐릭터 목록 뷰에 반영되지 않는 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterListViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/PlaceInfoTooltip/PlaceInfoTooltipWindow.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️
