Repository Team-Offroad/Offroad-iOS, pull requests merged in 2024-08, with the labels that each got.

#134 [Feat] #133 - 획득 캐릭터 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/baby.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/baby.imageset/Frame 1261160926.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_1.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_1.imageset/ios_[ver]get_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_2.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_2.imageset/ios_[ver]get_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_3.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/character_3.imageset/ios_[ver]get_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/check.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedCharacters/check.imageset/icon-check-circle-line-mono.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/Cell/AcquiredCharactersCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/View/AcquiredCharactersView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/ViewController/AcquiredCharactersViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#138 [Fix/#133] 코드리뷰 최종 반영
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/Cell/AcquiredCharactersCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/ViewController/AcquiredCharactersViewController.swift
Labels: 🫧 지원 🫧

#136 [Feat] #124 - 획득 칭호 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Literals/ColorLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/FontLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/icon_check_circle.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/icon_check_circle.imageset/icon_check_circle.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/icon_lock.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/icon_lock.imageset/icon_lock.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/img_tag.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CollectedTitles/img_tag.imageset/img_tag.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/Cell/AcquiredCharactersCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/View/AcquiredCharactersView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/Model/CollectedTitleModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/View/Cell/CollectedTitleCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/View/CollectedTitlesView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/ViewController/CollectedTitlesViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#137 [Feat] #128 - 마이 페이지 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_character_profile.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_character_profile.imageset/img_character_profile.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_character.imageset/img_collected_character.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_coupon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_coupon.imageset/img_collected_coupon.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_collected_title.imageset/img_collected_title.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_flag.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_flag.imageset/img_flag.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_setting.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_setting.imageset/img_setting.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_title_frame.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_title_frame.imageset/img_title_frame.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Model/MyPageMenuModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/Cell/MyPageMenuCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#143 [Feat] #130 - 설정 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/NavigationPopButton.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/icon_arrow.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/icon_arrow.imageset/icon_arrow.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_ cogwheel.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_ cogwheel.imageset/img_ cogwheel.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_loudspeaker.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_loudspeaker.imageset/img_loudspeaker.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Component/SettingBase/Cell/SettingBaseCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Component/SettingBase/SettingBaseView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Model/SettingBaseModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/Model/NoticePostModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/View/NoticePostView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/ViewController/NoticePostViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/View/NoticeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/ViewController/NoticeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/NotificationsList/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/NotificationsList/Notification/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/View/SettingView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/View/CollectedTitlesView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/ViewController/CollectedTitlesViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨
