Repository Team-Offroad/Offroad-iOS, pull requests merged in 2024-09, with the labels that each got.

#149 [Fix/#148] 권한 요청 문구(위치, 카메라) 변경
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#139 [Feat] #132 - 퀘스트 목록 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_checkBox.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_checkBox.imageset/icn_questList_checkBox.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_expendableCellChevron.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_expendableCellChevron.imageset/icn_placeList_expendableCellChevron.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_giftBox.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_giftBox.imageset/icn_questList_giftBox.svg
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Models/QuestListDummyDataManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#147 [Fix] #146 - 탭바 애니메이션 개선
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#150 [Feat] #140 - 약관 동의 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomView/TermsConsentPopupView.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_checked.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_checked.imageset/btn_checked.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_unchecked.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_unchecked.imageset/btn_unchecked.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/img_optional.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/img_optional.imageset/img_optional.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/img_required.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Onboarding/img_required.imageset/img_required.svg
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/Model/TermsModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/View/Cell/TermsListTableViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/View/TermsConsentView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#151 [Feat] #144 - 로그아웃, 탈퇴 팝업 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomView/TermsConsentPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/TitlePopup/View/TitlePopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/View/DeleteAccountView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/ViewController/DeleteAccountViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/LogOut/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Logout/View/LogoutView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Logout/ViewController/LogoutViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#152 [Feat] #127 - refresh token 재발급 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Adventure/AdventureService.swift
  Offroad-iOS/Offroad-iOS/Network/Auth/AuthAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Base/BaseTargetType.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemService.swift
  Offroad-iOS/Offroad-iOS/Network/Nickname/NicknameService.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Network/Quest/QuestService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/TokenIntercepter.swift
Labels: 🎀 혜린 🎀, Feat 💻, Fix ⚒️, Network 🌏

#126 [Fix] #125 - 닉네임 설정 뷰 1차 싱크 수정사항 해결
  Offroad-iOS/Offroad-iOS/Global/Components/CustomButton/StateToggleButton.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#156 [Feat] #153 - 칭호 목록 조회 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Mypage/img_new_tag.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Network/Emblem/DTO/Response/EmblemListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Emblem/EmblemService.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/View/Cell/CollectedTitleCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/View/CollectedTitlesView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/ViewController/CollectedTitlesViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#158 [Feat] #157 - 마이페이지 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/UserInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#161 [Feat] #160 - 마케팅 수신 동의 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/MarketingConsentRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/MarketingConsentResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/MarketingConsent/ViewController/MarketingConsentViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/View/TermsConsentView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/ViewController/TermsConsentViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#164 [Feat] #145 - 퀘스트 목록 뷰 서버 통신 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/QuestList/DTO/Response/QuestListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/QuestList/QuestListAPI.swift
  Offroad-iOS/Offroad-iOS/Network/QuestList/QuestListService.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Models/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Models/QuestListDummyDataManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Network 🌏

#165 [Feat] #154 - 장소 목록 뷰 서버 통신 구현
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Request/RegisteredPlaceRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceAPI.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Network 🌏

#166 [Feat] #159 - 회원 탈퇴 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Request/DeleteAccountRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/DeleteAccountResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/View/DeleteAccountView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/ViewController/DeleteAccountViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#168 [Feat] #163 - 획득 캐릭터 목록 조회 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIColor+.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_lock.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/img_lock.imageset/img_lock.svg
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/CharacterListAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/CharacterListService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/DTO/CharacterListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/Cell/AcquiredCharactersCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Character/ViewController/AcquiredCharactersViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/.gitkeep
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Network 🌏

#173 [Feat] #170 - 로그아웃 이벤트 구현
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeleteAccount/ViewController/DeleteAccountViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Logout/ViewController/LogoutViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#176 [Feat] #175 - LineHeight %값으로 적용할 수 있도록 UILabel 확장 함수 추가
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#178 [Fix] #177 - setLineSpacing(spacing:), setLineHeight(percentage:) 함수 수정
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
Labels: Fix ⚒️

#179 [Fix] #172 - 획득 쿠폰 상세 뷰UI 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponCodeInputPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCodeInputPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#182 [Setting] #181 - RxSwift, RxCocoa, RxRelay 라이브러리 추가
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Setting ⚙️

#171 [Feat] #169 - 캐릭터 상세 뷰 API 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterDetailAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterDetailService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterMotionAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterMotionService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/DTO/Response/CharacterDetailResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/DTO/Response/CharacterMotionResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/DTO/Response/CouponListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponCodeInputPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/BirthView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/GenderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/View/NicknameView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Feat 💻, Network 🌏

#187 [Setting/#186] RxSwift, RxCocoa, RxRelay 사용할 수 있도록 추가
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Setting ⚙️

#189 [Fix] #162 - 자잘한 버그 해결 및 수정사항 반영
  Offroad-iOS/Offroad-iOS/Global/Components/CustomSegmentedControl/CustomSegmentedControlButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#188 [Feat] #174 - OFRAlertController 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertAction.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertBackgroundView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertButton.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertController.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertViewModel.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/ZeroDurationAnimator.swift
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/ZeroDurationTransitionDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ios_ofrAlert_xmark.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ios_ofrAlert_xmark.imageset/ios_ofrAlert_xmark.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/ofrAlert/Contents.json
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Add ➕, Style 🎨

#193 [Fix] #190 - QA 수정사항 반영
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Responce/RegisteredPlaceResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Models/PlaceListDummyDataManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionViewCell.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#196 [Fix] #192 - PATCH로 변경으로 인한 회원가입 디코딩 수정
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Base/BaseService.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkResult.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/ProfileUpdateResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️

#198 [Fix] #194 - 쿠폰 상세 뷰 UI 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponCodeInputPopupView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCodeInputPopupViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩

#201 [Fix] #180 - QA 수정사항 반영
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomView/TermsConsentPopupView.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/DTO/Response/MarketingConsentResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Profile/ProfileService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/View/ChoosingCharacterCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/Component/CustomAlmostDoneProgressView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Onboarding/Model/TermsModel.swift
Labels: 🎀 혜린 🎀, Fix ⚒️

#200 [Fix] #191 - 공지사항 뷰 API 추가 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Extensions/String+.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Notice/DTO/Response/NoticeResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Notice/NoticeAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Notice/NoticeService.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Component/SettingBase/Cell/SettingBaseCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/Model/NoticePostModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/View/NoticePostView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/ViewController/NoticePostViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/ViewController/NoticeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️, Network 🌏

#195 [Fix] #185 - 닉네임 입력, 생년월일, 성별 뷰 QA 수정사항 반영
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/BirthViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/GenderViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Nickname/ViewController/NicknameViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️, Style 🎨

#203 [Feat] #199 - 획득 쿠폰 목록 뷰와 쿠폰 상세 뷰 UI개선 및 API 연결, 쿠폰 사용 API 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertController.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/DTO/Request/CouponRedemptionRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/DTO/Response/CouponRedemptionResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/AvailableCouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/UsedCouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/CouponDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩, Style 🎨, Network 🌏

#205 [Feat] #204 - 쿠폰 적용 API 연결(시도) 및 연속 팝업 구현
  Offroad-iOS/Offroad-iOS/Global/Components/PopupController/OFRAlertController.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/CouponService.swift
  Offroad-iOS/Offroad-iOS/Network/Coupon/DTO/Response/CouponListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Chore 🧩

#211 [Feat] #210 - CustomSegmentedControl 사용 뷰들의 UI 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomSegmentedControl/CustomSegmentedControl.swift
  Offroad-iOS/Offroad-iOS/Global/Components/CustomSegmentedControl/CustomSegmentedControlType.swift
  Offroad-iOS/Offroad-iOS/Global/Components/SegmentedControl/OFRSegmentedControl.swift
  Offroad-iOS/Offroad-iOS/Global/Components/SegmentedControl/OFRSegmentedControlButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponCollectionViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListCollectionViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/QuestMapViewController.swift
Labels: Feat 💻, Chore 🧩, Add ➕

#214 [Fix] #212 - 획득 캐릭터 목록 뷰 수정사항 반영
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/DTO/Response/CharacterDetailResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/DTO/CharacterListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
Labels: 🫧 지원 🫧, Fix ⚒️, Network 🌏
