Repository Team-Offroad/Offroad-iOS, pull requests merged in 2024-10, with the labels that each got.

#218 [Add] #208 - UIButton의 state에 따른 배경색 설정 (configuration 사용)
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIButton+.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/QuestMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestResult/Views/QuestResultView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Add ➕

#220 [Fix] #197 - 각종 버그 수정 및 개선사항 적용
  Offroad-iOS/Offroad-iOS/Global/Components/SegmentedControl/OFRSegmentedControl.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponList/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponList/icn_couponList_checkmark.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/CouponList/icn_couponList_checkmark.imageset/icn_couponList_checkmark.svg
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/Cell/UsedCouponCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/View/AcquiredCouponView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/AcquiredCouponViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩

#223 [Feat] #216 - 새로 바뀌는 탭바 디자인 대응
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/ORBTabBarShapeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Style 🎨

#226 [Feat] #222 - 기기 화면 비율에 따른 분기처리
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIScreen+.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩, Style 🎨

#228 [Fix/#219] 일부 iOS 버전에서 탭바가 숨겨질 때 이상하게 보이는 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Style 🎨

#230 [Feat] #227 - 토스트 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/OFRAlertAction.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/OFRAlertBackgroundView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/OFRAlertButton.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/OFRAlertController.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/OFRAlertView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/OFRAlertViewModel.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ORBOverlayViewController.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastManager.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastWindow.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ZeroDurationAnimator.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/ZeroDurationTransitionDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIViewController+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIWindowScene+.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#233 [Fix] #231 - 획득 캐릭터 목록 뷰, 캐릭터 상세 뷰 관련 코드 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/DTO/Response/CharacterMotionResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/DTO/CharacterListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterListView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/SelectMainCharacterView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#234 [Feat] #207 - 카카오 소셜 로그인 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
  Offroad-iOS/Offroad-iOS/Application/SceneDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
  Offroad-iOS/Offroad-iOS/Network/Auth/DTO/Request/SocialLoginRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/KakaoAuthManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Login/ViewController/LoginViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻, Network 🌏

#243 [Chore] #242 - 캐릭터 관련 API 코드 정리
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterDetailResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterInfoResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterMotionResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/StartingCharacterResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterDetailAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterDetailService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterMotionAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterDetail/CharacterMotionService.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/CharacterListAPI.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterList/CharacterListService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Character/ChoosingCharacter/ViewController/ChoosingCharacterViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩, Network 🌏

#241 [Refactor] #225 - 캐릭터 관련 뷰 리팩토링 및 개선
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastManager.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Toast/ORBToastWindow.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIViewController+.swift
  Offroad-iOS/Offroad-iOS/Global/NetworkMonitoring/NetworkMonitoringManager.swift
  Offroad-iOS/Offroad-iOS/Global/Protocols/SVGFetchable.swift
  Offroad-iOS/Offroad-iOS/Network/Character/CharacterService.swift
  Offroad-iOS/Offroad-iOS/Network/Character/DTO/Response/CharacterListResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Notice/NoticeService.swift
  Offroad-iOS/Offroad-iOS/Network/Place/PlaceService.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterDetailCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/Cell/CharacterListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/View/CharacterDetailView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterDetailViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewController/CharacterListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterDetailViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/CharacterList/ViewModel/CharacterListViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/ViewController/NoticeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Chore 🧩, Add ➕, Refactor 🏭, Network 🌏

#244 [Fix] #238 - 2차 QA 수정사항 반영
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_character.imageset/Frame 1261160897.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_coupon.imageset/Frame 1261160898.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_setting.imageset/Frame 1261160900.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MyPage/btn_title.imageset/Frame 1261160899.svg
  Offroad-iOS/Offroad-iOS/Network/Notice/DTO/Response/NoticeResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Component/MyPageCustomButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Model/MyPageMenuModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Component/SettingBase/SettingBaseView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/View/NoticePostView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/ViewController/NoticePostViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Title/View/CollectedTitlesView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/Cell/MyPageMenuCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/View/MyPageView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🎀 혜린 🎀, Fix ⚒️
