Repository Team-Offroad/Offroad-iOS, pull requests merged in 2025-03, with the labels that each got.

#476 [Feat] #469 - 일기 캘린더 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Presentation/Diary/Cell/CustomDiaryCalendarCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/View/DiaryView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewModel/DiaryViewModel.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#478 [Setting] #455 - Amplitude 라이브러리 설치 및 적용
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Amplitude/AmplitudeManager.swift
  Offroad-iOS/Offroad-iOS/Global/Components/Chat/ChatTextInput/ChatTextInputView.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Info_Dev.plist
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/ORBMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Setting ⚙️

#485 [Fix] #484 - AmplitudeManager 동작 범위 수정
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Amplitude/AmplitudeManager.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#481 [Feat] #477 - 일기 캘린더 pickerView 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/Diary/Modal/MonthPickerModalView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/MyDiaryManager/MyDiaryManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/View/DiaryView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/MonthPickerModalViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewModel/DiaryViewModel.swift
Labels: 🎀 혜린 🎀, Feat 💻

#486 [Chore] #480 - 리드미 최신화
  README.md
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Docs 📄

#488 [Feat] #483 - 기억빛 뷰 UI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/CustomView/CustomIntensityBlurView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/CustomView/MemoryLightGradientView.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UILabel+.swift
  Offroad-iOS/Offroad-iOS/Global/Extensions/UITextView+.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MemoryLight/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MemoryLight/icon_share.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MemoryLight/icon_share.imageset/icon_share.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MemoryLight/img_recommend_category.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/MemoryLight/img_recommend_category.imageset/img_recommend_category.svg
  Offroad-iOS/Offroad-iOS/Presentation/Diary/Cell/CustomDiaryCalendarCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryGuideViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewModel/DiaryViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/Cell/MemoryLightCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/Model/MemoryLightModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/View/MemoryLightView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewController/MemoryLightViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewModel/MemoryLightViewModel.swift
Labels: 🎀 혜린 🎀, Feat 💻, Style 🎨

#490 [Network] #489 - 일기 세팅 관련 api 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_diary_time_character.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_diary_time_character.imageset/img_diary_time_character.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_diary_time_character.imageset/img_diary_time_character@2x.png
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Setting/img_diary_time_character.imageset/img_diary_time_character@3x.png
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/DiarySetting/DTO/Response/DiarySettingCheckedResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/DiarySetting/DiarySettingAPI.swift
  Offroad-iOS/Offroad-iOS/Network/DiarySetting/DiarySettingService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/MyDiaryManager/MyDiaryManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryGuideViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewModel/DiaryViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DiaryTime/View/DiaryTimeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DiaryTime/ViewController/DiaryTimeViewController.swift
Labels: 🎀 혜린 🎀, Network 🌏

#492 [Network] #491 - 일기 캘린더/기억빛 api 연결
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/Diary/DTO/Response/DiaryCheckStatusResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Diary/DTO/Response/DiaryColorsResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Diary/DTO/Response/DiaryInitialDateResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Diary/DTO/Response/DiaryResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/Diary/DiaryAPI.swift
  Offroad-iOS/Offroad-iOS/Network/Diary/DiaryService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/MyDiaryManager/MyDiaryManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/View/DiaryView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/MonthPickerModalViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewModel/DiaryViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/Cell/MemoryLightCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewController/MemoryLightViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewModel/MemoryLightViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🎀 혜린 🎀, Network 🌏

#497 [Network] #495 - 일기 fcm api 연결
  Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/MyDiaryManager/MyDiaryManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewModel/MemoryLightViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Notice/NoticePost/ViewController/NoticePostViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/ORBMapViewController.swift
Labels: 🎀 혜린 🎀, Network 🌏

#494 [Feat] #493 - Amplitude 배포 환경에서만 동작
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Application/AppDelegate.swift
  Offroad-iOS/Offroad-iOS/Global/Amplitude/AmplitudeManager.swift
  Offroad-iOS/Offroad-iOS/Global/Resources/Info.plist
  Offroad-iOS/Offroad-iOS/Global/Resources/Info_Dev.plist
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻
