Repository Team-Offroad/Offroad-iOS, pull requests merged in 2025-05, with the labels that each got.

#522 [Feat] #519 - 오브의 추천 주문서(2안) GUI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/Alert/AlertView/ORBAlertBaseView.swift
  Offroad-iOS/Offroad-iOS/Global/Literals/StringLiterals.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/ViewController/ORBRecommendationMainViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/order/ORBRecommendationOrderView.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/order/ORBRecommendationOrderViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#526 [Fix] #525 - 오브 그라데이션 애니메이션 성능 개선
  Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationBaseBackground.swift
  Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationGradientLayer.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#528 [Fix] #527 - 채팅 입력창 레이아웃 수정
  Offroad-iOS/Offroad-iOS/Global/Components/Chat/ChatTextInput/ChatTextInputView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/ViewControllers/ORBCharacterChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️, Style 🎨

#530 [Fix] #529 - 채팅 말풍선 로딩이 끝나지 않는 문제 해결, 에러 추가
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#531 [Feat] #524 - 오브의 추천소 채팅 뷰 GUI (1안) 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/ChatLogCellCharacter.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/ChatLogCellCharacterLoading.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/ChatLogCellUser.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/Model/DeveloperModeSettingModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/ViewControllers/DeveloperModeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/Views/DeveloperModeSwitchCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Custom Transition/ORBRecommendationChatPresentationFloatingView.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Custom Transition/ORBRecommendationChatViewDismissingTransition.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Custom Transition/ORBRecommendationChatViewPresentingTransition.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Custom Transition/ORBRecommendationViewPresentationController.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/DiffableDataSource/ORBRecommendationChatDataSource.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/ViewControllers/ORBRecommendationChatViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatBackgroundView.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatExampleQuestion.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatView.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/ViewController/ORBRecommendationMainViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#532 [Feat] #437 - 앱 업데이트 유도 기능 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/Base/NetworkService.swift
  Offroad-iOS/Offroad-iOS/Network/MinimumSupportedVersion/DTO/MinimumSupportedVersionResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/MinimumSupportedVersion/MinimumSupportedVersionAPI.swift
  Offroad-iOS/Offroad-iOS/Network/MinimumSupportedVersion/MinimumSupportedVersionService.swift
  Offroad-iOS/Offroad-iOS/Presentation/Splash/ViewController/SplashViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻

#537 [Chore] #533 - 사소한 코드 변화
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/chat/Views/ORBRecommendationChatView.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/order/ORBRecommendationOrderView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Chore 🧩

#539 [Fix] #538 - 다른 기기에서 회원 탈퇴한 경우, 스플래시 화면에서 다음으로 진행되지 않는 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/Login/AuthManager/TokenIntercepter.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#535 [Feat] #520 코스퀘스트 목록 셀 GUI 적용
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_cafe.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_cafe.imageset/Frame 1261161495.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_dday_bubble.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_dday_bubble.imageset/Rectangle 509268.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_park.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_park.imageset/🏞️.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_restaurant.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_restaurant.imageset/🍽️.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_show.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/QuestList/icn_questList_show.imageset/🤹🏻‍♀️.svg
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Models/CourseQuest.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/CourseQuestCollectionViewCell.swift
Labels: 🫧 지원 🫧, Add ➕, Style 🎨

#545 [Refactor] #540 - ORBSegmentedControl 리팩토링 및 기능 추가
  Offroad-iOS/Offroad-iOS/Global/Components/SegmentedControl/ORBSegmentedControl.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Coupon/ViewController/CouponListViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/ViewControllers/PlaceListViewController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Refactor 🏭

#555 [Fix] #554 - 장소 목록 뷰의 각 세그먼트가 반대로 표시되는 문제 해결
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️
