Repository Team-Offroad/Offroad-iOS, pull requests merged in 2025-04, with the labels that each got.

#499 [Feat] #498 - 기억빛 공유하기 기능 구현
  Offroad-iOS/Offroad-iOS/Global/Extensions/UIView+.swift
  Offroad-iOS/Offroad-iOS/Presentation/Diary/ViewController/DiaryViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MemoryLight/ViewController/MemoryLightViewController.swift
Labels: 🎀 혜린 🎀, Feat 💻

#504 [Fix] #503 - 위치 인증 타겟별 분기처리
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Fix ⚒️

#507 [Feat] #506 - 개발자 모드 구현(개발용 앱에서만)
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/Overlay/LogPrinter/LogPrinterManager.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/Model/DeveloperModeSettingModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/ViewControllers/DeveloperModeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/Views/DeveloperModeNormalCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/Views/DeveloperModeSwitchCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/DeveloperMode/Views/DeveloperModeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/Model/SettingBaseModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/MyPage/Settings/ViewController/SettingViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/ORBMapViewModel.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻

#509 [Refactor] #479 - 오브 지도 뷰 분리
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/ORBMap/ORBMapView.swift
  Offroad-iOS/Offroad-iOS/Global/Components/ORBMap/PlaceInfoTooltip/PlaceInfoTooltip.swift
  Offroad-iOS/Offroad-iOS/Global/Components/ORBMap/PlaceInfoTooltip/PlaceInfoTooltipHelper.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewControllers/AdventureMapViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/ViewModel/AdventureMapViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/AdventureMapView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestMap/Views/ORBMapHelper.swift
  Offroad-iOS/Offroad-iOS/Presentation/TabBar/ViewControllers/OffroadTabBarController.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Refactor 🏭

#487 [Feat] #475 - 퀘스트 목록에서의 코스 퀘스트 컴포넌트 생성
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Models/CourseQuest.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/CourseQuestCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/IconLabelStackView.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/QuestListCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/QuestListEmptyPlaceholder.swift
Labels: 🫧 지원 🫧, Feat 💻, Style 🎨

#511 [Refactor] #496 - 퀘스트 목록 뷰의 아코디언 셀 기능 라이브러리로 분리
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/ViewControllers/QuestListViewControllers.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/CourseQuestCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/Components/QuestListCollectionViewCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Add ➕, Style 🎨

#513 [Feat] #512 - 오브의 추천소 그라데이션 효과 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationBaseBackground.swift
  Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationGradientLayer.swift
  Offroad-iOS/Offroad-iOS/Global/Components/ORBRecommendationGradient/ORBRecommendationGradientStyle.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/CharacterChat/Views/ORBCharacterChatBox.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogCell.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨

#514 [Refactor] #510 - 채팅 로그 뷰 리팩토링
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Request/CharacterChatPostRequestDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatGetResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Network/CharacterChat/DTO/Response/CharacterChatPostResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Model/CharacterChatItem.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewControllers/CharacterChatLogViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/ViewModel/CharacterChatLogViewModel.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/CharacterChatLogView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/CharacterChatLogFooter.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/ChatLogCellCharacter.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/ChatLogCellCharacterLoading.swift
  Offroad-iOS/Offroad-iOS/Presentation/Chat/ChatLog/Views/ReusableView/ChatLogCellUser.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Refactor 🏭

#516 [Feat] #515 - 오브의 추천소 메인 화면 GUI 구현
  Offroad-iOS/Offroad-iOS.xcodeproj/project.pbxproj
  Offroad-iOS/Offroad-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_orbRecommendation_home.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/Home/btn_orbRecommendation_home.imageset/btn_orbRecommendation_home.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/icn_orbRecommendationMain_message.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/icn_orbRecommendationMain_message.imageset/icn_orbRecommendationMain_message.svg
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/icn_orbRecommendationMain_title.imageset/Contents.json
  Offroad-iOS/Offroad-iOS/Global/Resources/Assets.xcassets/icn_orbRecommendationMain_title.imageset/icn_orbRecommendationMain_title.svg
  Offroad-iOS/Offroad-iOS/Network/Place/DTO/Responce/RegisteredPlaceResponseDTO.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/View/HomeView.swift
  Offroad-iOS/Offroad-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/ViewController/ORBRecommendationMainViewController.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/Views/ORBRecommendationMainView.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/Views/ORBRecommendationMainViewToolBar.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/Views/ORBRecommendationMessageButton.swift
  Offroad-iOS/Offroad-iOS/Presentation/ORBRecommendation/main/Views/ORBRecommendedContentView.swift
  Offroad-iOS/Offroad-iOS/Presentation/PlaceList/Views/PlaceListCell.swift
  Offroad-iOS/Offroad-iOS/Presentation/QuestList/Views/QuestListCollectionView.swift
Labels: 🧑🏻‍💻 민성 🧑🏻‍💻, Feat 💻, Style 🎨
